### ISSUE TITLE
Does not appear under 'misc'

### ISSUE THREAD

**Issue by RCheesley** [alekseyp/octobercms-googletagmanager#3] opened 2019-04-18 15:27 UTC
Hi there,

I can't find where to configure this, no entry appears under 'misc' in the back-end after I installed the plugin?

**Comment by alekseyp** [comment] 2019-04-18 20:06
Are you use it's installed? Try to login/logout from admin interface.

**Comment by RCheesley** [comment] 2019-04-18 21:45
Yes, it's installed and I see it in the list of plugins, and I can
uninstall it via manage plugins.

**Comment by alekseyp** [comment] 2019-04-22 23:15
Try to login/logout from admin interface.

**Comment by RCheesley** [comment] 2019-04-26 15:49
Thanks, I have done this but it still does not appear anywhere in Misc.

**Comment by RCheesley** [comment] 2019-04-29 22:08
In my Googling it seems this file https://github.com/alekseyp/octobercms-googletagmanager/blob/master/Plugin.php hasn't been updated in many years. Other extensions seem to suggest problems with the settings which necessitated an update in more recent versions of OCMS.

See here for an example which fixed the issue for another plugin: https://octobercms.com/plugin/support/anandpatel-seoextension/my-settings-not-showing-anywhere-in-backend - does this give you any kind of insights into why it might not be showing in the settings?

**Comment by alekseyp** [comment] 2019-04-30 02:20
What version are you running?

I've just tested it on latest Build 453 and it's working without any issues.

Can you try to install it via cli to see if there any errors?

```
$ php artisan plugin:install AlekseyP.GoogleTagManager
Downloading plugin: AlekseyP.GoogleTagManager
Unpacking plugin: AlekseyP.GoogleTagManager
Migrating plugin...
AlekseyP.GoogleTagManager
- v1.0.1:  First version of Google Tag Manager (GTM) plugin.
- v1.0.2:  Support composer.
- v2.0.1:  Switching to latest GTM code installation. Extra placeholder needed.
```

<img width="899" alt="Screen Shot 2019-04-29 at 10 17 44 PM" src="https://user-images.githubusercontent.com/1569335/56937842-d58a6400-6acc-11e9-8062-197bad25b86c.png">

**Comment by RCheesley** [comment] 2019-04-30 09:17
Hi there, I am currently on build 447 of OctoberCMS. No errors on installation.

php artisan plugin:install AlekseyP.GoogleTagManager
Downloading plugin: AlekseyP.GoogleTagManager
Unpacking plugin: AlekseyP.GoogleTagManager
Migrating plugin...
AlekseyP.GoogleTagManager
- v1.0.1:  First version of Google Tag Manager (GTM) plugin.
- v1.0.2:  Support composer.
- v2.0.1:  Switching to latest GTM code installation. Extra placeholder needed.

**Comment by alekseyp** [comment] 2019-05-10 16:48
I've tested it multiple times and couldn't reproduce it.
Try to install it on fresh system and see if it works.

**Comment by alekseyp** [comment] 2019-05-24 02:39
I'll close it for now. Feel free to share more information later.

**Closed as completed by alekseyp** 2019-05-24 02:39 UTC
Labels: help wanted
